name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew assemble

      - run: ./gradlew check
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-reports
          path: '**/build/reports/*'
          retention-days: 5

      - run: ./gradlew jacocoTestReport

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - run: ./gradlew -PRELEASE_SIGNING_ENABLED=false publishToMavenLocal
